# Generated by Django 5.0.2 on 2024-02-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_medicine', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
