# Generated by Django 5.0.2 on 2024-02-25 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('Phone_number', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('physical_address', models.CharField(max_length=30)),
                ('work_place', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('Phone_number', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('physical_address', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(max_length=130)),
                ('Role', models.CharField(choices=[('CEO', 'CEO'), ('CRDO', 'CRDO'), ('CRO', 'CRO'), ('TEAM LEADER', 'TEAM LEADER'), ('TECHNICIAN', 'TECHNICIAN'), ('LOGISTIC', 'LOGISTIC'), ('DRIVER', 'DRIVER')], max_length=100)),
                ('emergency_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.emergencycontact')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_lead', to='Employee.employees')),
                ('team_members', models.ManyToManyField(related_name='team_members', to='Employee.employees')),
            ],
        ),
    ]
