# Generated by Django 5.0.2 on 2024-02-25 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_company', models.CharField(max_length=60)),
                ('Phone_number', models.CharField(max_length=30)),
                ('Phone_number_2', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=60)),
                ('Tin_number', models.CharField(max_length=60)),
                ('Main_contact_person_full_name', models.CharField(max_length=30)),
                ('Main_contact_person_phone_number', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('physical_address', models.CharField(max_length=100)),
                ('Structural_detail', models.CharField(max_length=60)),
                ('companies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.companies')),
            ],
        ),
    ]
