# Generated by Django 5.0.2 on 2024-02-25 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients', '0001_initial'),
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=30)),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AssignedTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_members', models.ManyToManyField(to='Employee.employees')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.team')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_of_visit', models.CharField(choices=[('Major spray application visit', 'Major spray application visit '), ('Minor spray application visit', 'Minor spray application visit  '), ('Major non-spray application visit', 'Major non-spray application visit'), ('Minor non-spray application visit', 'Minor non-spray application visit'), ('Major pesticide Spray and Rodenticide Treatment', 'Major pesticide Spray and Rodenticide Treatment'), ('Major pesticide Non-Spray and Rodenticide Treatment', 'Major pesticide Non-Spray and Rodenticide Treatment'), ('Rodent application visit', 'Rodent application visit'), ('Room spray treatment', 'Room spray treatment'), ('Room Non-spray treatment', 'Room Non-spray treatment'), ('Structural Fumigation', 'Structural Fumigation'), ('Furniture Fumigation', 'Furniture Fumigation'), ('Inspection for quotation', 'Inspection for quotation'), ('Regular follow-up and monitoring ', 'Regular follow-up and monitoring'), ('Major spray + Non-spray treatment ', 'Major spray + Non-spray treatment')], max_length=200)),
                ('current_condition', models.CharField(max_length=30)),
                ('locatiion_to_be_covered', models.CharField(max_length=60)),
                ('Additional_task', models.CharField(max_length=30)),
                ('detail', models.CharField(max_length=30)),
                ('assigned_teams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requests.assignedteams')),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.clients')),
                ('schedules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requests.schedules')),
            ],
        ),
    ]
